name: Publish on NPM
on:
    push:
        branches: [release]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: npm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'
            - run: npm npm
            - run: npm prettier-check
            - run: npm build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
